from exceptions.MAvitoException import MAvitoException


class AuthException(MAvitoException):
    pass